name: Release application

on:
  release:
    types: [created]

defaults:
  run:
    shell: pwsh

jobs:
  build:
    name: "Release build"
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "9.0.x"

      - name: Build the application
        run: dotnet build vmr-generator.sln --configuration Release

      - name: Build the ClickOnce installer
        run: |
          dotnet publish -c Release 1
            -p:Version=${{ steps.get_version.outputs.version-without-v }}.0 1
            -p:ApplicationVersion=${{ steps.get_version.outputs.version-without-v }}.0 1
            -p:PublishProfile=Properties/PublishProfiles/ClickOnceProfile.pubxml

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: ./publish/setup.exe
